[package]
name = "socket_toolbox"
version = "0.2.0"
authors = ["Bomou He <paakmau@outlook.com>"]
edition = "2018"

[dependencies]
bytes = "1"
log = "0.4"
hex = "0.4.3"
simplelog = "0.10.0"
socket2 = "0.4.1"
strum = { version = "0.21", features = ["derive"] }
thiserror = "1.0.29"
eframe = "0.14.0"
